language: go
go:
- 1.6
sudo: false
before_script:
- 'mkdir -p $GOPATH/bin && wget -q https://github.com/barnybug/go-castv2/releases/download/0.0.1/upx -O $GOPATH/bin/upx && chmod +x $GOPATH/bin/upx'
script:
- make deps
before_deploy:
- make release
deploy:
  provider: releases
  api_key:
    secure: nmqbnVuj7XpuUMs5YmB2X+/Dkq5I2hoWaIUSO5Okse7D8iYW0fWPeqR5xMy3ctSlHJgNarMx3qPJZmr+lJAuwT7xZhvW2kFOJE7Ra/nJgLtuWOMu4zrJ2cLNYTgE4fN3jag5VkgnuB4Ax57QZESssWKLvyBVA7ePaV/HXe1hX7k=
  file:
  - release/cast-linux-386
  - release/cast-linux-amd64
  - release/cast-linux-arm
  - release/cast-mac-amd64
  - release/cast-windows-386.exe
  - release/cast-windows-amd64.exe
  on:
    repo: barnybug/go-castv2
    tags: true
